Added CardsViewPager component
TegetaApp/TegetaAndroidApp pull request #3
Opened 2022-02-10 13:57 UTC by fnrngg

2022-02-11 15:25 UTC, Rogavactive requested changes

2022-02-11 15:25 UTC, Rogavactive commented on presentation/src/main/java/ge/tegeta/tegetaandroidapp/view/cardsviewpager/CardsViewPager.kt
> +    }
მე მგონი, სჯობს მხოლოდ ადაპტერი გადასცე (თუ რამე აუცილებელი ფუნქიები აქვს ინტერფეისით, თუ არა და RecyclerView.Adapter არის ეს მგონი) და ადაპტერის ლოგიკის დასეტვა უკვე გამომყენებლის ვალდებულება იყოს. შეგიძლია ადაპტერი ცალკე დაუწერო, ცალკე ფექიჯად ოღონდ. ბოლო 3 ხაზი, ადაპტერისთვის რაღაცის დასეტვა არ არის აუცილებელი თუ ადაპტერს გარეთ გაიტან.

2022-02-11 15:25 UTC, Rogavactive commented on presentation/src/main/java/ge/tegeta/tegetaandroidapp/view/cardsviewpager/CardsViewPagerAdapter.kt
> +        binder?.bind(getItem(position), holder.itemView)
რისთვის გამოიყენება ეს ბაინდერი? თუ ადაპტერის ლოგიკას ვიუდან გავიტანთ ბაინდერის აუცილებლობაც აღარ იქნება აქ. 
პ.ს.: გლაიდის სურათების დაქეშირებას წინასწარ დავიწყებთ, API რესფონსის მოსვლისთანავე შეიძლება გადმოწეროს გლაიდმა და შეინახოს სამომავლოდ.

2022-02-11 15:25 UTC, Rogavactive commented on presentation/src/main/java/ge/tegeta/tegetaandroidapp/home/fragment/HomeFragment.kt
> +            "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYWFRgWFhIYGBgYGBgYGBgYGBgYGBgYGBgZGRgYGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGhISGjQkISE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ
გატესტვას როცა მორჩები, არ დაგავიწყდეს წაშლა ;დ მეც მავიწყდება ხოლმე, დიდი პრობლემა არ არის მაგრამ მაინც.

2022-02-12 09:58 UTC, fnrngg commented on presentation/src/main/java/ge/tegeta/tegetaandroidapp/home/fragment/HomeFragment.kt
> +            "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYWFRgWFhIYGBgYGBgYGBgYGBgYGBgYGBgZGRgYGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGhISGjQkISE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ
დროებით იყოს სანამ რეალური დატა გვექნება

2022-03-29 22:34 UTC, Rogavactive approved these changes

2022-03-29 22:35 UTC, merged